### ISSUE TITLE
Blender 3.1.x - Bake_PBR view_transform mode is blocking script execution

### ISSUE THREAD

**Issue by EpicTommyLahitte** [oscurart/Blender-30-Addons#1]
Line302, Linear Raw is blocking the execution of **oscurart_bake_pbr.py** in Blender 3.1.2 
User is able to Bake BRP if line 302 is replaced by the following: 

    **bpy.context.scene.view_settings.view_transform = "Standard"**

**Comment by oscurart** [comment]
Hi Epic.
Yes... you re right. Im using the Troy luts...
I'm going to add an exception for that.

Give me 1 day, I will do it.

**Comment by oscurart** [comment]
fixed!
