### ISSUE TITLE
"Needs at least two selected objects" When selecting 2 or more objects and doing OscurartTools > DistributeObjects

### ISSUE THREAD

**Issue by made-by-chris** [oscurart/Blender-30-Addons#12]
Blender v4.0.0 
installed via option 1 - dragging directory into scripts/addons (**NOTE: NOT** in the scripts directory as mentioned, as it didn't show up)

**Comment by nendo-minting** [comment]
Same here. Blender 4.0.2

**Comment by oscurart** [comment]
To use distribute you must do it from properties panel.
![image](https://github.com/oscurart/Blender-30-Addons/assets/15130162/8a47bd4d-4378-4f74-9325-8b57b4e203ae)
