### ISSUE TITLE
Overlap UVs throws Python error (list index out of range) 

### ISSUE THREAD

**Issue by jantin1** [oscurart/Blender-30-Addons#2]
This is essentially the same as [#9 of 28 addons issue](https://github.com/oscurart/Blender-28-Addons/issues/9). When I try to use the "Overlap UVs" button from the UV context menu -> oscurart, the button throws error. I tried to select to overlap objects in the UV window and in the edit window; I have the Oscurart properties menu open. I'm working on Windows 10, GeForce GTX 1650 within Lenovo Legion laptop. I attach screenshot of the issue with the thrown error, how can I make the tool work?
![image](https://user-images.githubusercontent.com/91844627/172060363-0da38fb4-924c-4dbf-8264-1bc54fb80c8a.png)

**Comment by oscurart** [comment]
hi Janin, how are you?
sorry for the delay. Blender has this option without plugins now!
