### ISSUE TITLE
Install of Oscurart 3.0 in Blender 3.4.1 does not work

### ISSUE THREAD

**Issue by DaniAngel** [oscurart/Blender-30-Addons#4]
Greetings,
I am using Blender 3.4.1 on Linux Mint 20.3 Cinnamon.  I have installed Blender-30-Addons using the Install Addons button in the preferences/addons window.  When I search for oscurart, nothing is listed.  When I check the addons folder in my system hierarchy, I see that the Blender-30-Addons folder is there.  What do I need to do to get this installed?

**Comment by oscurart** [comment]
http://oscurart.blogspot.com/2020/12/addon-oscurart-tools.html

**Comment by DaniAngel** [comment]
Thank you for the reply.  This is still not working.  I have tried it with v28 and v30, to no avail. I have hit the refresh button in Blender Addon Settings and it's still not listed.  Any more suggestions?  See attached pics...
![oscuart_in_folder](https://user-images.githubusercontent.com/41321230/210283016-fcb5362e-f74f-49f5-8807-2e6da44d97a6.
![oscuart_not_listed_in_blender](https://user-images.githubusercontent.com/41321230/210283020-f9affe96-ad81-4331-a4b5-c95bf5b504f8.png)
png)

**Comment by DaniAngel** [comment]
I think I just got it straightened out.  I grabbed the parent folder and not oscuart_tools...Thank you...

**Comment by imperfectlink** [comment]
Seems like it works but distribute objects is broken.

**Comment by oscurart** [comment]
Hi! 
Are you following the tutorial steps? because I'm working with the last build, and it works fine.

Don't use INSTALL, follow the tutorial! hahahaha
