### ISSUE TITLE
Bake Error: Base Color not found

### ISSUE THREAD

**Issue by enzyme69** [oscurart/Blender-30-Addons#5]
Trying to bake Sanctus Material but failed.

Blend below:
[sanctus_oscurart_bake_001.blend.zip](https://github.com/oscurart/Blender-30-Addons/files/11468587/sanctus_oscurart_bake_001.blend.zip)

**Comment by oscurart** [comment]
![image](https://github.com/oscurart/Blender-30-Addons/assets/15130162/a77a9bcf-c6b4-42c6-b6c5-49ddd9f2dae7)
Yes, it makes sense, because Bake PBR only works with principled shader.
Yesterday I made an upgrade. Now if you make a mistake blender tells you how fix it!
