### ISSUE TITLE
feature suggestion: render token add support for date and time

### ISSUE THREAD

**Issue by Zijian-Wang** [oscurart/Blender-30-Addons#8]
Hello, thanks for making this add-on! 
A small suggestion: when using the render token, can I use params like "$MM-$DD" or "$hh:$mm:$ss" to represent "month-date" or "hour-minutes-seconds"? This would be a great help as to making the single frame render easy to manage and also make sure that there's no overwrite files? 

I'll upload a screen shot of the same function from Cinema4D just to make my suggestions clearer: 
![image](https://github.com/oscurart/Blender-30-Addons/assets/19564332/46652893-1e95-428e-a36e-1a6402513e1d)

Thanks again.

**Comment by Zijian-Wang** [comment]
In case it helps: 

c4d's token naming: 
YYYY - _year full_
YY - _year short_
MM - _month_
DD - _date_
hh - _hour_
mm - _minute_
ss - _second_

**Comment by oscurart** [comment]
Hi Zijian, how are you?
I have never thought on that. It could be a good idea.

This addition is not hard, I will put it in the future features, but I can't promise anything.

Thanks for your suggestion!
