### ISSUE TITLE
Installed Oscurart Add-on in 3.6, but where is the Tool?

### ISSUE THREAD

**Issue by Davexx** [oscurart/Blender-30-Addons#9]
Hi,
I zipped the latest oscurart_tools folder in my downloads directory and installed/enabled the add-on with no issues.  
I even added a scripts directory at c:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons_contrib\

I cannot find the the tool in the interface.  It is not listed in the right-click Object Context Menu in the 3Dview, nor is it listed in the sidebar.
Is there another place where I should look for the Oscurart Tools menu?

**Comment by jayliu50** [comment]
I had to restart Blender after installing. 

Then I opened up Add-Ons, and checked Oscurart Tools.

Finally, I was able to access the tools by right clicking in the 3D viewport.

**Comment by Davexx** [comment]
I found  the issue:
Ensure that the folders: **files, mesh, object**, and **render** are in the root of "oscurart_tools" folder and make sure the folder is named "oscurart_tools".  
This folder should be in: 
c:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ folder, or else the OscurartTools menu will not show up in the Object Context Menu (right-click menu), nor will it allow you to see the add-on in your Add-ons folder to enable it.  

It might be a bit confusing to those who, from this Github page, click on the green "<>Code" button and then use "download ZIP" as the zip file will not set up correctly.  The instructions in the Read.md file are accurate but there are a few "gotchas".

**Comment by oscurart** [comment]
you can found the instructions in the readme file.
